name: Build and Publish Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
env:
  DOCUMENTATION_PATH: ${{ github.workspace }}/my-website
  EXILED_REFERENCES_URL: https://www.exiled.host/build_deps/References.zip
  EXILED_REFERENCES_PATH: ${{ github.workspace }}/References

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-website-
      
      - name: Install dependencies
        run: yarn --cwd ${{ env.DOCUMENTATION_PATH }} install --frozen-lockfile
      
      - name: Build website
        run: yarn --cwd ${{ env.DOCUMENTATION_PATH }} build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
